version: '3'

services:
  reverse-proxy:
    image: traefik:v2.3
    command:
      - "--entrypoints.web.address=:80"
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.email=${EMAIL}"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/app/acme.json"
    ports:
      - "80:80"
      - "443:443"
    restart: always
    container_name: reverse-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/app
    logging:
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - proxy

networks:
  proxy:
    external: true