version: '3'

services:
  reverse-proxy:
    image: traefik:v2.1
    command: --certificatesResolvers.le.acme.email=${EMAIL} --certificatesResolvers.le.acme.tlsChallenge.entryPoint=web --certificatesResolvers.le.acme.storage="/app/acme.json"
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./:/app
    logging:
      options:
        max-size: "200k"
        max-file: "10"