version: '3'
services:
  registry:
    image: registry:2
    restart: unless-stopped
    volumes:
      - ./registry:/var/lib/registry
      - ./usersfile:/app/usersfile
    container_name: registry
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.mydomain.com`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=mytlschallenge"
      - "traefik.http.middlewares.registry.basicauth.usersfile=/app/usersfile"
    networks:
      - proxy

networks:
  proxy:
    external: true

# generate basic auth entry in usersfile
# docker run --rm -ti xmartlabs/htpasswd username password >> usersfile
