version: "3.5"

services:
#  cardano-node:
#    image: inputoutput/cardano-node:1.29.0
#    command: [
#        "run",
#        "--config", "/config/config.json",
#        "--database-path", "/data/db",
#        "--socket-path", "/ipc/node.socket",
#        "--topology", "/config/topology.json"
#    ]
#    volumes:
#      - ./server/config/network/${NETWORK:-mainnet}/cardano-node:/config
#      - ./server/config/network/${NETWORK:-mainnet}/genesis:/genesis
#      - node-db:/data
#      - node-ipc:/ipc
#    restart: on-failure
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "400k"
#        max-file: "20"

  ogmios:
    image: cardanosolutions/ogmios:latest-mainnet
    build:
      context: .
      target: ogmios
      cache_from: [cardanosolutions/ogmios:latest]
    restart: on-failure
    command: [/opt/cardano/cnode/files
        "--host", "0.0.0.0",
        "--node-socket", "/ipc/node0.socket",
        "--node-config", "/node-config/config.json"
    ]
    volumes:
      - ./ogmios-config:/config
      - /opt/cardano/cnode/sockets:/ipc
      - /opt/cardano/cnode/files:/node-config
    ports:
      - "1337:1337"

#volumes:
#  node-db:
#  node-ipc:
